pipeline {
    agent { 
        node {
            label 'agent-alpine'
        }
    }
    triggers {
        pollSCM '*/5 * * * *'
    }
    stages {
        stage('Setup') { 
            steps {
                echo "Setting up environment.."
                sh '''
                apk add --no-cache python3 py3-pip
                python3 --version
                pip --version
                '''
            }
        }
        stage('Build') {
            steps {
                echo "Building.."
                sh '''
                cd 02_project/myapp
                pip install -r requirements.txt
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                cd 02_project/myapp
                python3 hello.py
                python3 hello.py --name=Leslie
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Delivering....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}
